[build]
  command = "npm ci --ignore-scripts && npm run build"
  publish = ".next"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  
  [plugins.inputs]
    # Explicitly disable static export
    generateStaticHTML = false
    buildOnly = false

[build.environment]
  NODE_VERSION = "20.11.0"
  NPM_VERSION = "10"
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"
  DISABLE_ESLINT = "false"
  ENABLE_AI_FEATURES = "true"
  ENABLE_VIDEO_GENERATION = "true"
  ENABLE_SOCIAL_PUBLISHING = "true"
  # Force Next.js server mode - prevent static export
  NETLIFY_NEXT_PLUGIN_SKIP = "false"
  NEXT_EXPORT = "false"
  # Production mode - use real API keys from Netlify environment variables
  # DO NOT override environment variables here - let Netlify UI values take precedence

[functions]
  external_node_modules = ["openai", "@supabase/supabase-js", "elevenlabs"]
  node_bundler = "esbuild"

[functions."api/ai/generate"]
  timeout = 60

[functions."api/video/generate"]
  timeout = 300

[functions."api/elevenlabs/generate"]
  timeout = 60

[functions."api/auth/login"]
  timeout = 30

[functions."api/health"]
  timeout = 10

[functions."api/flow/generate-copy"]
  timeout = 26

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; font-src 'self' fonts.gstatic.com; style-src 'self' 'unsafe-inline' fonts.googleapis.com; img-src 'self' data: https: blob:; object-src 'none'; base-uri 'self'; form-action 'self'; frame-ancestors 'none'; upgrade-insecure-requests; script-src 'self' 'unsafe-inline' 'unsafe-eval' 'unsafe-hashes'; connect-src 'self' https://*.supabase.co wss://*.supabase.co https://api.openai.com https://api.elevenlabs.io https://api.creatomate.com https://graph.facebook.com https://api.twitter.com https://api.linkedin.com"

# Headers for fonts
[[headers]]
  for = "*.woff"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "*.ttf"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "*.eot"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"

# Headers for CSS
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "text/css; charset=UTF-8"
