[build]
  publish = ".next"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "10"

# Build hook for production environment
[context.production]
  command = "npm run build"

[context.deploy-preview]
  command = "npm run build"

# Functions configuration for API routes
[functions]
  directory = ".netlify/functions"

# Redirect rules for Next.js
[[redirects]]
  from = "/_next/*"
  to = "/_next/:splat"
  status = 200

# Handle API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/nextjs"
  status = 200

# Handle all other routes through Next.js
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/nextjs"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"

# Cache static assets
[[headers]]
  for = "/_next/static/*"  
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
