[build]
  command = "npm run build"
  
[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "10"

# Environment variables - make sure these are set in Netlify UI
[build.environment.production]
  NODE_ENV = "production"
