[build]
  command = "npm ci --ignore-scripts && npm run build"
  publish = ".next"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20.11.0"
  NPM_VERSION = "10"
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"
  DISABLE_ESLINT = "false"
  ENABLE_AI_FEATURES = "true"
  ENABLE_VIDEO_GENERATION = "true"
  ENABLE_SOCIAL_PUBLISHING = "true"
  # Security: All sensitive values should be set in Netlify UI Environment Variables
  # These are build-time placeholders only - real values must be configured in deployment
  JWT_SECRET = "demo_jwt_secret_key_for_build_only_12345678901234567890"
  OPENAI_API_KEY = "sk-demo_openai_key_placeholder_for_build_testing_only"
  # Supabase Demo Configuration - Replace with real values in Netlify UI
  NEXT_PUBLIC_SUPABASE_URL = "https://your-project.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "your-anon-key-here"
  # For demo mode, disable auth requirements
  DEMO_MODE = "true"
  DISABLE_AUTH = "true"

[functions]
  external_node_modules = ["openai"]
  node_bundler = "esbuild"

[functions."api/flow/generate-copy"]
  timeout = 26

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; font-src 'self' fonts.gstatic.com; style-src 'self' 'unsafe-inline' fonts.googleapis.com; img-src 'self' data: https: blob:; object-src 'none'; base-uri 'self'; form-action 'self'; frame-ancestors 'none'; upgrade-insecure-requests; script-src 'self' 'unsafe-inline' 'unsafe-eval' 'unsafe-hashes'; connect-src 'self' https://*.supabase.co wss://*.supabase.co https://api.openai.com https://api.elevenlabs.io https://api.creatomate.com https://graph.facebook.com https://api.twitter.com https://api.linkedin.com"

# Headers for fonts
[[headers]]
  for = "*.woff"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "*.ttf"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "*.eot"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"

# Headers for CSS
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "text/css; charset=UTF-8"
